[workspace]
resolver = "2"
members = ["cli","compiler"]

[workspace.package]
name = "website"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
toml = "1"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio = { version = "1.51.1", features = ["full"] }
futures = "0.3.32"

# Optimizations go brrr.
# Does it really matter for such a small website? of course it does
[profile.opt]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = 3
# Still optimize the dev-build plenty
[profile.dev]
opt-level = 3
