[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
compiler.path = "../compiler"
clap = { version = "4.6.0", features = ["derive"] }
serde.workspace = true
toml.workspace = true
axum = "0.8.8"
tower-http = { version = "0.6.8", features = ["fs", "set-header", "trace", "compression-br"] }
tokio.workspace = true
futures.workspace = true
notify = "8.2.0"
tokio-stream = { version = "0.1.18", features = ["sync"] }
eyre = "0.6"
color-eyre = "0.6.5"
dircpy = "0.3.20"
