[package]
name = "compiler"
version.workspace = true
edition.workspace = true

[dependencies]

# Configuration loading
serde.workspace = true
toml.workspace = true

# Creating errors
thiserror.workspace = true

# Logging
tracing.workspace = true

# Compiling markdown
markdown.workspace = true
codemap = "0.1.3"
html-escape = "0.2.13"
url = "2.5.8"

# Compiling styles
grass = "0.13.4"

# Use tokio and futures to make integration with the CLI much nicer.
# The server is based on axum, and it's async-first soo I'd rather not fight with
# that today.
tokio.workspace = true
futures.workspace = true

# Templating engine.
liquid = { version = "0.26.11", features = ["liquid-lib"] }
