[package]
name = "compiler"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
tracing.workspace = true
markdown.workspace = true
render = "0.3.1"
html-escape = "0.2.13"
grass = "0.13.4"
codemap = "0.1.3"
url = "2.5.8"
# Use tokio and futures to make integration with the CLI much nicer.
# The server is based on axum, and it's async-first soo I'd rather not fight with
# that today.
tokio.workspace = true
futures.workspace = true
